___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [4]:
import numpy as np

#### Create an array of 10 zeros 

In [5]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an array of 10 ones

In [6]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

In [10]:
arr = np.ones(10)
arr +4

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Create an array of the integers from 10 to 50

In [15]:
np.linspace(10,51,42)

array([ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,
        21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,
        32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,
        43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.])

#### Create an array of all the even integers from 10 to 50

In [18]:
arr= np.linspace(10,51,42)

IndexError: arrays used as indices must be of integer (or boolean) type

#### Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [26]:
np.array([[1,0,0],[0,1,0],[0,0,1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy to generate a random number between 0 and 1

In [32]:
number = np.random.rand()

0.3238170926144335

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [33]:
np.random.randn(25)

array([-0.07951964, -2.19176562, -0.67415609,  1.02687509,  2.17446532,
        0.49602294, -1.06490341, -0.19109262,  0.21755701,  0.27165035,
        0.58145096,  1.08173885, -0.99880042,  1.144864  , -0.80571456,
        0.51174548, -0.40385728,  0.30614378,  1.75969271, -0.81122996,
        0.20554586, -1.15550101, -0.16998955,  1.83660575,  1.47585522])

#### Create the following matrix:

In [69]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [49]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [51]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [53]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [59]:
mat[3,4]

20

20

In [63]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [31]:
mat[]

In [46]:
m

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [64]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [65]:
mat.std()

7.2111025509279782

#### Get the sum of all the columns in mat

In [70]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!